### ISSUE TITLE
Allow free-form text with an optional picker/typeahead suggest when filling in org-unit

### ISSUE THREAD

**Issue by ssalb1z** [alphabetworkers/alphabetworkersunion.org#147]
Right now the org unit we ask for here: https://github.com/alphabetworkers/alphabetworkersunion.org/blob/main/frontend/src/element/signup.ts#L809

is totally free-form.

A rigid picker probably isn't what we want since it makes things harder for TVCs and employees in less common reporting structures - but having a general type-ahead/suggestion mechanism might be helpful

**Comment by jonahbron** [comment]
I agree that this would improve the new member experience.  It's not likely not feasible unfortunately as it would require obtaining an external list of orgs within Google.  Feel free to comment and reopen if you know of such an available list.
