### ISSUE TITLE
Update form text around email & phone-number

### ISSUE THREAD

**Issue by ssalb1z** [alphabetworkers/alphabetworkersunion.org#148]
Feedback from discord: "I'm not sure it's fair to say we use phone numbers "rarely." In the PNW, at least, we do fairly regular text outreach."

"Speaking of which I noticed the message permission box is for both email and text. I had previously interpreted that as being for SMS only but I can see why we need it for email too. I guess we need to make the meaning of that field clear to everyone who messages members"

**Comment by shiibainu** [comment]
Currently form reads:
Personal phone: "We sometimes contact each other via phone call or text message, particularly if we can't reach you via any other methods."
Would you like SMS updates?: "Yes, I want to receive updates from CWA International. Message & data rates may apply. Visit https://www.cwa-union.org/sms-terms for Terms & Conditions and Privacy Policy."

I _think_ this is clarified adequately enough to close the issue? So I am closing it. Thanks y'all for your work on this!
