### ISSUE TITLE
Reported issue with Plaid in production

### ISSUE THREAD

**Issue by jonahbron** [alphabetworkers/alphabetworkersunion.org#157]
Per @realjenny , someone reported that they were unable to signup with Plaid.  I ran a test myself, and it is replicatable.  It seems we're configured incorrectly.  Here's the log output:

```
{
  "outcome": "ok",
  "scriptName": "signup-worker",
  "exceptions": [],
  "logs": [
    {
      "message": [
        {
          "display_message": null,
          "documentation_url": "https://plaid.com/docs/?ref=error#invalid-input-errors",
          "error_code": "INVALID_PUBLIC_TOKEN",
          "error_message": "provided public token is for the wrong Plaid environment. expected \"sandbox\", got \"production\"",
          "error_type": "INVALID_INPUT",
          "request_id": "OH4CIiGhrxMEb6v",
          "suggested_action": null
        }
      ],
    },
 /* ............... */
  },
  "id": 0
}
```

Upon inspection of the ENV vars, we were configured to point to the sandbox API.  However, changing that to production did not fix the issue.  I think we don't have all production keys in place across front-end and back-end.

**Comment by jonahbron** [comment]
Ashok gave me access to the prod Plaid account and I re-set all of the keys.  Unfortunately it seems that the Plaid account isn't connected to the Stripe account, because Stripe says that the payment token created by Plaid does not exist.

**Comment by undefinedseance** [comment]
this got fixed
