### ISSUE TITLE
Card sign form: Make office location a required field

### ISSUE THREAD

**Issue by shiibainu** [alphabetworkers/alphabetworkersunion.org#161]
We've been seeing some signs with no office location indicated — this is a pretty important field for employment verification purposes (helps to disambiguate dupes), and everyone should have an office location, even if that location is "REMOTE". Request to make this field required.

**Comment by mattrubin** [comment]
Closed by https://github.com/alphabetworkers/alphabetworkersunion.org/pull/258, as per https://github.com/alphabetworkers/alphabetworkersunion.org/pull/204#issuecomment-1325566064
