### ISSUE TITLE
Create an international section

### ISSUE THREAD

**Issue by realjenny** [alphabetworkers/alphabetworkersunion.org#20]
Currently, the international section of the FAQ is a bit weak; we should strengthen it by linking to efforts in other countries where we can to give people pointers.

go/works-councils has some source data.

TBD: Should it be a stand-alone page or simply added to the FAQ?

**Comment by shiibainu** [comment]
(doing some issue clean-up)

New site FAQ includes info about UNI as well as links to info about Ireland, Japan, Korea, Poland, Switzerland. I think that probably covers this for now. Closing.
