### ISSUE TITLE
timezone issue at end of month

### ISSUE THREAD

**Issue by crschmidt** [alphabetworkers/alphabetworkersunion.org#226]
function getBillingAnchor(): Date {
const now = new Date();
  now.setUTCDate(1);
  now.setUTCMonth(now.getUTCMonth() + 1);
  // Setting 8 hours means that we'll get the right day on the invoice if
  // the Stripe account is in UTC (a likely default), Eastern (local 1400),
  // or Pacific time
  now.setUTCHours(8);
  now.setUTCMinutes(0);
  now.setUTCSeconds(0);
}

At 9:01pm Eastern time, this returns April 1st, rather than March 1st, which Stripe doesn't accept.

Rather than using getUTCMonth (which will roll over sooner than the user's local clock) I think that we want to use getMonth(). After that, we're setting everything directly, so this should be fine. (setUTCMonth vs. setMonth will be the same, since we're passing an explicit number.)

**Comment by mattrubin** [comment]
Fixed by https://github.com/alphabetworkers/alphabetworkersunion.org/pull/233
