### ISSUE TITLE
Accessibility of homepage

### ISSUE THREAD

**Issue by realjenny** [alphabetworkers/alphabetworkersunion.org#24]
Feedback sent to contact@:

The next and previous buttons are on the main landing page.  Just below the navigation region, there is some large text that says We are Alphabet Workers who stand united.  The buttons ( look like < and >) are invisible.  There are two ways to make them appear.  

1) Hover Mouse of the "We are Alphabet Workers" text, or
2) Tab from the navigation bar.  Fosu will move on to each button in order, and the focused button will appear.  
The buttons appear to change two different lines of text (Alphabet worker, empathetic, BIPOC, etc) and (truste each other, fight against totalitarianism, etc).

The problem for a screen reader user is there is no real context for these buttons.  Previous what?  Next what?  And any changes these buttons make are not readily apparent if you are not reading the screen.  You have to navigate to the button, then back to the text, etc. to understand what is going on.  

After a closer visual inspection, I think the intent of the design is to provide a bit of interactivity and highlight the diversity of categories of people and what the people are doing.  It just wasn't very clear when using a screen reader.

**Comment by jonahbron** [comment]
This issue is obsolete now that the main website has been migrated to another platform.
