### ISSUE TITLE
Plaid Asking for Too Much Information

### ISSUE THREAD

**Issue by stephenmcmurtry** [alphabetworkers/alphabetworkersunion.org#264]
<img width="514" alt="plaid" src="https://github.com/alphabetworkers/alphabetworkersunion.org/assets/12698957/272b3646-6861-46ae-a0d2-84838dd56502">

While testing the fixed join form, the Plaid integration—what we want people to use because we pay smaller fees with ACH—was asking me to grant AWU a lot of information: balances, transactions, account names, etc.

It also gave me the option to share many more accounts than my checking with AWU: even my mortgage!

<img width="461" alt="plaid2" src="https://github.com/alphabetworkers/alphabetworkersunion.org/assets/12698957/1eaf5a1d-d6f1-4ecf-88b5-fbe4b16d18ae">

Ideally it should just authorize a payment from a checking or savings account as desired. Can we trim the perms (no more transactions) and maybe use a different payment-focused workflow?

**Comment by shiibainu** [comment]
@jonahbron are you familiar with this? I got access to Plaid and poked around but don't have any answers yet. I can reach out to Plaid support but wanted to check with you first.

**Comment by shiibainu** [comment]
@hongalex could you post your conclusions from your investigation on this issue here and close it out?

**Comment by jonahbron** [comment]
Plaid is now removed from the flow entirely, we only use Stripe's bank account verification flow.  Closing this as obsolete, thank you for reporting.
