### ISSUE TITLE
Card sign form: Strip extra whitespace from Name

### ISSUE THREAD

**Issue by shiibainu** [alphabetworkers/alphabetworkersunion.org#266]
Lots of folks signing up with a trailing space in their name, which can make things tricky down the line for automations that match on name and such. Request that when importing data into Airtable / Stripe we strip any trailing spaces.

**Comment by shiibainu** [comment]
Ooh I realized that part of the issue was the formula for how we calculate Full Name in the Membership Data base, but after correcting that there are still some cases floating through where I think it's user error, so I think this issue still stands.

**Comment by jonahbron** [comment]
Thanks for addressing @mattrubin!
