### ISSUE TITLE
Orchestrate subproject npm scripts

### ISSUE THREAD

**Issue by jeffposnick** [alphabetworkers/alphabetworkersunion.org#81]
As per a conversation with @jonahbron and @realjenny, there's a need to orchestrate the various `npm` scripts that are run across the multiple subprojects that currently live in the `signup` branch.

I'm going to submit a PR that does this via a top-level script which will `exec()` out to the various subprojects scripts. If any of the underlying scripts error, the top-level script will error as well. This should require minimal refactoring of the subprojects.

(Something like https://developers.cloudflare.com/workers/tutorials/manage-projects-with-lerna is also an option, but my experience with `lerna` has been that it's good when you need to release subprojects to `npm` with cross-dependencies, but too much overhead for simpler tasks.)

**Comment by jonahbron** [comment]
I think this is obsolete with the move away from Cloudflare Pages for the website itself.
