### ISSUE TITLE
signup form changes

### ISSUE THREAD

**Issue by junefish** [alphabetworkers/alphabetworkersunion.org#83]
### tweaks and fixes for [signup form](https://signup.alphabetworkersunion.pages.dev/join/)

- [x] `Preferred name.  Enter your name so we know what you prefer` is both redundant phrasing and also the usage of "preferred" is a bit of a transphobic dogwhistle.
    *suggested fix*: `Name.  Enter the name you want union members to use when communicating with you`
- [x] `Employement` is misspelt in the **Where do you work?** section
- [x] `Alphabet employer` lists multiple non-AMER entities.  This is both unnecessary and misleading as non-AMER workers are not eligible for AWU membership.
    *suggested fix*: remove all non-AMER entities from the `Alphabet employer` list, and add `only workers in the US or Canada are eligible` as explanation text to the `Country` field in the **Address** section.
- [x] The explanation text under the question `Do you have reports?` doesn't clarify whether dotted-line reports should count as reports.
    *suggested fix*: add clarification as to whether dotted reports count to `Individuals with (non-intern/student researcher) reports face a different risk profile when joining a union. If you do, we will reach out to you with more info.`

**Comment by shiibainu** [comment]
I believe these are generally resolved now (perhaps by Syed), the one item remaining is that the "Alphabet employer" still has some non-US/canada entities, but given that the Country item does indicate that only workers in US/Can are eligible, I think this is probably fine to leave as is for now. Closing.
